###
# The observer is presented with a value on each trial, which represents the 
# strenght of a sensory observation.
# The obs is generated by either a "target" trial, or a "catch" trial, where
# only the mask is presented. The observer does not know 


# Simulate data for SDT model

n <- 250 # total number of trials
p_target <- 0.7 # prob of target trial 
n_target <- n*p_target
trials_unmixed <- c(
  rep(1, n_target),
  rep(0, n - n_target)
)

trial_seq <- sample(trials_unmixed, size = n, replace = FALSE)

# alternative, if we did not care to ensure a specific number of target trials:
#trial_seq <- rbinom(n = n, size = 1, prob = p_target) 


# mu_target specify how different z-score noise and target 
# observations are; mu_noise is implicitly 0 here

mu_target <- .5

perceived_val <- rnorm(n = n, mean = trial_seq*mu_target, sd = 1)

threshold <- 0.75 # what the threshold which the observer uses to respond "yes"

data <- tibble(
  obs = perceived_val,
  type = trial_seq,
  threshold = threshold
) %>% 
  mutate(
    resp = if_else(
      obs > threshold, 1, 0
    ),
    resp_cat = case_when(
      type == 1 & resp == 1 ~ "hit",
      type == 0 & resp == 1 ~ "false alarm",
      type == 0 & resp == 0 ~ "correct rejection",
      type == 1 & resp == 0 ~ "miss",
    ),
    type_f = if_else(
      type == 1, "target", "noise"
    )
  )
data %>% glimpse()

experimental_data <- data %>% select(type, type_f, resp, resp_cat)
experimental_data
rates <- experimental_data %>% 
  group_by(type_f, resp_cat) %>% 
  summarise(
    count = n()
  ) %>% 
  group_by(type_f) %>% 
  mutate(
    prop = count/sum(count)
  )

rates



# phi function: pnorm()
# inverse phi function: qnorm()


