---
title: "Week1"
format: html
editor: visual
---
load packages
```{r}
library(tidyverse)
library(glue)
```


Simulate data
```{r}
###
# The observer is presented with a value on each trial, which represents the 
# strenght of a sensory observation.
# The obs is generated by either a "target" trial, or a "catch" trial, where
# only the mask is presented. The observer does not know 


# Simulate data for SDT model

n <- 250 # total number of trials
p_target <- 0.7 # prob of target trial 
n_target <- n*p_target
trials_unmixed <- c(
  rep(1, n_target),
  rep(0, n - n_target)
)

trial_seq <- sample(trials_unmixed, size = n, replace = FALSE)

# alternative, if we did not care to ensure a specific number of target trials:
#trial_seq <- rbinom(n = n, size = 1, prob = p_target) 


# mu_target specify how different z-score noise and target 
# observations are; mu_noise is implicitly 0 here

mu_target <- 1

perceived_val <- rnorm(n = n, mean = trial_seq*mu_target, sd = 1)

threshold <- 0.75 # what the threshold which the observer uses to respond "yes"

data <- tibble(
  obs = perceived_val,
  type = trial_seq,
  threshold = threshold
) %>% 
  mutate(
    resp = if_else(
      obs > threshold, 1, 0
    ),
    resp_cat = case_when(
      type == 1 & resp == 1 ~ "hit",
      type == 0 & resp == 1 ~ "false alarm",
      type == 0 & resp == 0 ~ "correct rejection",
      type == 1 & resp == 0 ~ "miss",
    ),
    type_f = if_else(
      type == 1, "target", "noise"
    )
  )

data %>% glimpse()
```

Summarise
```{r}
exp_data <- data %>% select(type, type_f, resp, resp_cat)
exp_data

rates <- exp_data %>% 
  group_by(type_f, resp_cat) %>% 
  summarise(
    count = n(),
    .groups = "drop"
  ) %>% 
  group_by(type_f) %>% 
  mutate(
    prop = count/sum(count)
  )

rates


```

Calc d' and threshold from simulated data; can we estimate the latent values?

phi function: pnorm()
inv phi function: qnorm()
```{r}
rates <- rates %>% 
  mutate(
    z_score = qnorm(p = prop, mean = 0, sd = 1)
  )

hit_z_score <- rates %>% filter(resp_cat == "hit") %>% pull(z_score)
miss_z_score <- rates %>% filter(resp_cat == "false alarm") %>% pull(z_score)

d_prime <- hit_z_score - miss_z_score

c <- ((hit_z_score + miss_z_score)/2)*-1
c_rel_to_zero <- d_prime - c


rates %>% 
  mutate(across(c(prop, z_score), round, 2)) %>% 
str_glue("d' is estimated to: {round(d_prime, 3)}")
str_glue("c is estimated to {round(c, 3)}")
str_glue("threshold is estimated to {round(c_rel_to_zero, 3)}")

```

























